### PR TITLE
PR to merge Friendship v2 into development

### PR DESCRIPTION
**Pull request by UmairAhmad125**
In this milestone, we optimized the friendships.
Details about the project are mentioned in the readme file

### CODE REVIEW

**Review by andresporras3423 — CHANGES_REQUESTED** [review]
### Status: Changes Required :recycle:
**Hello Aldana Longhi & Umar Chingani** 
Nice job with your first submission :muscle:  :muscle: 
Your page meets most of the requirements :clap: :clap: :clap:  
We still need to fix some details:

- [ ] In timeline, user should only be able to see their own comments and their friends comments.
- [ ] In user_spec add description for each test.
- [ ] In timeline, each post should include a count of the total number of upvotes.
- [ ] In friendship_process_spec you have only one test where you do too many things (create first, create second user, login, send request). Create a test for each action: create a user, login, send request, accept request, reject request, etc.
- [ ] Add a screenshot in tour README file.

Please request another review once you are ready! :+1: 

Happy coding :relaxed:

Oscar Andrés Russi Porras

**Comment by UmairAhmad125** [comment]
> ### Status: Changes Required 
> **Hello Aldana Longhi & Umar Chingani**
> Nice job with your first submission  
> Your page meets most of the requirements   
> We still need to fix some details:
> 
> * [ ]  In timeline, user should only be able to see their own comments and their friends comments.
> * [x]  In user_spec add description for each test.
> * [ ]  In timeline, each post should include a count of the total number of upvotes.
> * [x]  In friendship_process_spec you have only one test where you do too many things (create first, create second user, login, send request). Create a test for each action: create a user, login, send request, accept request, reject request, etc.
> * [ ]  Add a screenshot in tour README file.
> 
> Please request another review once you are ready! 
> 
> Happy coding 
> 
> Oscar Andrés Russi Porras

Hey @andresporras3423 
First of all, you mentioned someone else's name on our PR
We completed all the requirements as mentioned in [pathwright](https://ibb.co/DKPY9rN)

**Review by tirthajyoti-ghosh — CHANGES_REQUESTED** [review]
# Changes required 🛑 

## Impressive progress so far 💪! Thanks for making all the changes 👏.

Everything is working fine - the login/logout, new user registration, reject/accept the friendship, inverse friendship. You have taken care of all the requirements. Well done!

### However, we need to work on some changes before we can merge.

As pointed out by the previous reviewer, you have written only one feature test which is actually testing more than one feature. It's always a good idea to break your tests into smaller tests so that your tests only handle one scenario. For eg., one feature test for login, one for logout, for the new user signing up, for accepting/rejecting friendships, etc. Just like you tested each association and validation in separate tests. 

This way you will always be sure how your app will behave in the wild.

Please separate the feature test into multiple tests. Each of those tests must be responsible for testing only one feature.

Your project looks absolutely fantastic. Just make these changes and apply for another code review.

Happy coding 👨‍💻 

*Need help? Shoot me a message on Slack - [@Ghosh](https://app.slack.com/client/T47CT8XPG/DRDM6LAQN/user_profile/URB1MHXK6)*
<hr>

**Tirthajyoti Ghosh**

[GitHub](https://github.com/tirthajyoti-ghosh) | [LinkedIn](https://www.linkedin.com/in/tirthajyoti-ghosh/) | [Twitter](https://twitter.com/terrific_ghosh)

**Comment by Dandush03** [comment]
# Status: :rocket: Project Approved :green_circle: 
### Great work, keep it up
## :tophat: Happy Coding :computer:

**Pull request merged**
